Repository kubernetes-incubator/external-storage, pull requests merged in 2018-11, with the labels that each got.

#1041 Fix some typos in README.md
  gluster/file/README.md
Labels: approved, area/gluster/glusterfs, cncf-cla: yes, lgtm, size/S

#1042 Add containerized build process.
  local-volume/provisioner/Makefile
  local-volume/provisioner/deployment/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1047 Add bit about nfs 1-replica limitation
  nfs/docs/deployment.md
Labels: approved, area/nfs, cncf-cla: yes, lgtm, size/XS

#1040 Upgrade to use kubernetes common base image.
  Makefile
  local-volume/provisioner/Makefile
  local-volume/provisioner/deployment/docker/Dockerfile
  local-volume/provisioner/deployment/docker/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1051 Fix typo in file name
  nfs/docs/usage.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1050 fix: grant provisioner access to endpoint resource
  ceph/rbd/deploy/rbac/clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1048 Fix some typo in volume-snapshotting-proposal.md
  snapshot/doc/volume-snapshotting-proposal.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1055 Update function name
  local-volume/provisioner/pkg/common/common.go
  local-volume/provisioner/pkg/deleter/jobcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1039 Enhancements to helm template
  Makefile
  local-volume/helm/README.md
  local-volume/helm/examples/baremetal-namespace.yaml
  local-volume/helm/generated_examples/baremetal-cleanbyjobs.yaml
  local-volume/helm/generated_examples/baremetal-namespace.yaml
  local-volume/helm/generated_examples/baremetal-nodeselector.yaml
  local-volume/helm/generated_examples/baremetal-prometheus.yaml
  local-volume/helm/generated_examples/baremetal-resyncperiod.yaml
  local-volume/helm/generated_examples/baremetal-tolerations.yaml
  local-volume/helm/generated_examples/baremetal-with-resource-limits.yaml
  local-volume/helm/generated_examples/baremetal-without-rbac.yaml
  local-volume/helm/generated_examples/baremetal.yaml
  local-volume/helm/generated_examples/gce-pre1.9.yaml
  local-volume/helm/generated_examples/gce-retain.yaml
  local-volume/helm/generated_examples/gce.yaml
  local-volume/helm/generated_examples/gke.yaml
  local-volume/helm/hack/update-generated.sh
  local-volume/helm/hack/verify-generated.sh
  local-volume/helm/provisioner/templates/namespace.yaml
  local-volume/helm/provisioner/templates/provisioner.yaml
  local-volume/helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
