Repository kubernetes-incubator/external-storage, pull requests merged in 2019-08, with the labels that each got.

#1200 update quickstart instructions
  aws/efs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1194 [cephfs-provisioner] Provisioner should not fail if secret exists
  ceph/cephfs/cephfs-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1208 Update nfs to lib 4 and client-go w GetReference fix
  .travis.yml
  deploy.sh
  nfs/Makefile
  nfs/go.mod
  nfs/go.sum
  nfs/pkg/volume/provision.go
  nfs/pkg/volume/provision_test.go
  nfs/test/e2e/go.mod
  repo-infra/verify/go-tools/verify-govet.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1211 [nfs-provisioner] Fix link failed.
  nfs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
