Repository kubernetes-incubator/external-storage, pull requests merged in 2019-09, with the labels that each got.

#1217 Fix NFS e2e to build using build/run.sh
  nfs/test/e2e/nfs.go
  nfs/test/e2e/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1214 make the fsid device setting configurable
  nfs/cmd/nfs-provisioner/main.go
  nfs/docs/deployment.md
  nfs/pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1215 Improve dockerfile and update Ganesha version
  nfs/deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M
