Repository kubernetes-incubator/external-storage, pull requests merged in 2019-05, with the labels that each got.

#1172 Dont report error from both caller and callee.
  gluster/file/cmd/glusterfile-provisioner/glusterfile-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1124 Deprecation notice for README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#1170 Make env also used while naming provisioner.
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1171 Dont report erorr from both caller and callee
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/S
