Repository kubernetes-incubator/external-storage, pull requests merged in 2019-10, with the labels that each got.

#1230 Updated API Version, Added selector field.
  nfs-client/deploy/deployment-arm.yaml
  nfs-client/deploy/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1231 Updated API Version & Added selector.
  nfs-client/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1219 [aws-efs] Update base image to Alpine 3.10
  aws/efs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1234 Update efs to lib 4, fix klog vs glog crash
  aws/efs/Dockerfile
  aws/efs/Makefile
  aws/efs/cmd/efs-provisioner/efs-provisioner.go
  aws/efs/go.mod
  aws/efs/go.sum
  test.sh
Labels: approved, area/aws/efs, cncf-cla: yes, lgtm, size/L
