Repository kubernetes-incubator/external-storage, pull requests merged in 2019-11, with the labels that each got.

#1248 set NFS_V4_RECOV_ROOT to /export
  nfs/deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1186 Remove explicit mention of `[heketi]` string in error message
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/M

#1179 Remove ServiceAccount from deployment yaml files
  nfs-client/deploy/deployment-arm.yaml
  nfs-client/deploy/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1190 [nfs-provisioner] Add error check for endpoints list when validating …
  nfs/pkg/volume/provision.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#1158 Fix a broken link
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#1087 Fix namespace and bump to Deployment apps/v1
  nfs-client/README.md
  nfs-client/deploy/deployment-arm.yaml
  nfs-client/deploy/deployment.yaml
  nfs-client/deploy/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/S

#1239 Updated API Version, Added selector field.
  ceph/cephfs/deploy/non-rbac/deployment.yaml
  ceph/cephfs/deploy/rbac/deployment.yaml
  ceph/rbd/deploy/non-rbac/deployment.yaml
  ceph/rbd/deploy/rbac/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1255 Update rbac.yaml
  nfs-client/deploy/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1196 Add ability to build nfs-provisioner for ARM
  .gitignore
  nfs/Makefile
  nfs/deploy/docker/arm/Dockerfile
  nfs/deploy/docker/x86_64/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1241 Add missing ports and NFSv3 Support
  nfs/deploy/kubernetes/deployment.yaml
  nfs/deploy/kubernetes/pod.yaml
  nfs/deploy/kubernetes/statefulset.yaml
  nfs/pkg/server/server.go
  nfs/pkg/volume/provision.go
  nfs/pkg/volume/provision_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1213 Update CEPH_VERSION to nautilus
  ceph/cephfs/Dockerfile
  ceph/cephfs/Dockerfile.release
  ceph/rbd/Dockerfile
  ceph/rbd/Dockerfile.release
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1260 fix broken links
  openebs/README.md
  snapshot/doc/examples/aws/README.md
  snapshot/doc/volume-snapshotting-proposal.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1245 This change is to correct issue #1243.
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/S
