Repository kubernetes-incubator/external-storage, pull requests merged in 2019-02, with the labels that each got.

#1088 Build efs-provisioner in a multi stage Dockerfile
  .dockerignore
  aws/efs/Dockerfile
  aws/efs/Makefile
  aws/efs/README.md
Labels: approved, area/aws/efs, cncf-cla: yes, lgtm, size/S

#1090 Make nfs-client ARM deployment consistent with regular deployment.
  nfs-client/deploy/deployment-arm.yaml
  nfs-client/deploy/objects/deployment-arm.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1135 [Cephfs] Improved docs
  ceph/cephfs/README.md
  ceph/cephfs/deploy/README.md
  ceph/cephfs/deploy/rbac/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1133 Fix secret type in rbd readme
  ceph/rbd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
