Repository kubernetes-incubator/external-storage, pull requests merged in 2019-01, with the labels that each got.

#1094 [cephfs] Remove extraneous 'kubernetes' from claimRoot
  ceph/cephfs/example/class.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1108 Added timeout for rbd commands execution and improved logging
  ceph/rbd/cmd/rbd-provisioner/main.go
  ceph/rbd/pkg/provision/provision.go
  ceph/rbd/pkg/provision/rbd_util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1109 Added new flag to control image name
  ceph/rbd/cmd/rbd-provisioner/main.go
  ceph/rbd/pkg/provision/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1106 Replace glog with klog
  Gopkg.lock
  Gopkg.toml
  aws/efs/cmd/efs-provisioner/efs-provisioner.go
  ceph/cephfs/cephfs-provisioner.go
  ceph/rbd/cmd/rbd-provisioner/main.go
  ceph/rbd/pkg/provision/provision.go
  ceph/rbd/pkg/provision/rbd_util.go
  digitalocean/cmd/digitalocean-provisioner/main.go
  digitalocean/pkg/volume/delete.go
  digitalocean/pkg/volume/provision.go
  flex/cmd/flex-provisioner/main.go
  flex/pkg/volume/delete.go
  flex/pkg/volume/driver-call.go
  flex/pkg/volume/provision.go
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
  gluster/file/cmd/glusterfile-provisioner/glusterfile-provisioner.go
  gluster/glusterfs/cmd/glusterfs-simple-provisioner/main.go
  gluster/glusterfs/pkg/volume/delete.go
  gluster/glusterfs/pkg/volume/exec.go
  gluster/glusterfs/pkg/volume/provision.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1113 Switch Ceph provisioner to use Image Format v2 by default.
  ceph/rbd/pkg/provision/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1114 Add klog.InitFlags(nil) to main.go
  aws/efs/cmd/efs-provisioner/efs-provisioner.go
  ceph/cephfs/cephfs-provisioner.go
  ceph/rbd/cmd/rbd-provisioner/main.go
  digitalocean/cmd/digitalocean-provisioner/main.go
  flex/cmd/flex-provisioner/main.go
  gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go
  gluster/file/cmd/glusterfile-provisioner/glusterfile-provisioner.go
  gluster/glusterfs/cmd/glusterfs-simple-provisioner/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1115 fixed typo in README
  aws/efs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1116 Clarify nfs provisioner quickstart steps regarding RBAC
  nfs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
